#!/bin/sh

# helper functions

print_usage() {
    # Print script usage

    cat <<EOF
Usage: $0 [-n NAME]
Play notes with your keyboard!

    -n, --note              note-playing function name (possible values: 'play', 'bell', 'print', default: 'play')
EOF
}

# parse args

function='play'

unparsed=''

for arg in "$@"; do
    case $arg in
    -n | --name)
        shift
        function="$1"
        ;;
    -h | --help)
        print_usage
        exit
        ;;
    *) unparsed="$unparsed $1" ;;
    esac
    shift
done

set -- $unparsed

# get script directory, works in most simple cases
scriptdir="$(dirname -- "$0")"

# import library functions
# shellcheck disable=SC1090
. "$scriptdir/beeplaylib.sh"

emit_tty | beeplay "note_$function"
